package io.hyperfoil.tools.jjq.mapper.processor;

import java.util.List;

/**
 * Generates Java source code for a record/POJO mapping class.
 * Uses raw StringBuilder — no code generation library dependency.
 */
final class MappingCodeGenerator {

    private MappingCodeGenerator() {}

    /**
     * Generate the complete Java source for a _JqMapping class.
     */
    static String generate(String packageName, String recordSimpleName, String recordQualifiedName,
                           String mappingClassName, List<JqMapperProcessor.ComponentInfo> components) {
        var sb = new StringBuilder(1024);

        // Package declaration
        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        // Imports
        sb.append("import io.hyperfoil.tools.jjq.JqProgram;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.GeneratedMapping;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.JqMapper;\n");
        sb.append("import io.hyperfoil.tools.jjq.value.*;\n");
        sb.append("\n");
        // Additional imports for specific types
        boolean needsBigDecimal = components.stream().anyMatch(c -> c.typeName().equals("java.math.BigDecimal"));
        boolean needsList = components.stream().anyMatch(c -> c.typeName().startsWith("java.util.List"));
        boolean needsMap = components.stream().anyMatch(c -> c.typeName().startsWith("java.util.Map"));
        boolean needsOptional = components.stream().anyMatch(c -> c.typeName().startsWith("java.util.Optional"));
        boolean needsArrayList = needsList;

        if (needsBigDecimal) sb.append("import java.math.BigDecimal;\n");
        if (needsList) sb.append("import java.util.List;\n");
        if (needsArrayList) sb.append("import java.util.ArrayList;\n");
        if (needsMap) {
            sb.append("import java.util.Map;\n");
            sb.append("import java.util.LinkedHashMap;\n");
        }
        if (needsOptional) sb.append("import java.util.Optional;\n");
        if (needsBigDecimal || needsList || needsMap || needsOptional) sb.append("\n");

        // Class declaration
        sb.append("/**\n");
        sb.append(" * Generated mapping for {@link ").append(recordQualifiedName).append("}.\n");
        sb.append(" * Do not edit — regenerated by jjq-mapper-processor.\n");
        sb.append(" */\n");
        sb.append("public final class ").append(mappingClassName);
        sb.append(" extends GeneratedMapping<").append(recordSimpleName).append("> {\n\n");

        // Static JqProgram fields for each non-ignored component
        for (var comp : components) {
            if (!comp.ignored()) {
                sb.append("    private static final JqProgram P_")
                  .append(comp.name().toUpperCase())
                  .append(" = JqProgram.compile(\"")
                  .append(escapeJava(comp.jqExpr()))
                  .append("\");\n");
            }
        }
        // Static converter fields for @JqConverter annotations
        for (var comp : components) {
            if (!comp.ignored() && comp.converterClass() != null) {
                sb.append("    private static final io.hyperfoil.tools.jjq.mapper.ValueConverter<?> CONV_")
                  .append(comp.name().toUpperCase())
                  .append(" = new ").append(comp.converterClass()).append("();\n");
            }
        }
        sb.append("\n");

        // fromJqValue method
        generateFromJqValue(sb, recordSimpleName, components);

        // toJqValue method
        generateToJqValue(sb, recordSimpleName, components);

        // appendJson method — direct-to-JSON, bypasses JqValue tree
        generateAppendJson(sb, recordSimpleName, components);

        // appendJsonBytes method — direct-to-bytes, bypasses JqValue tree
        generateAppendJsonBytes(sb, recordSimpleName, components);

        // type() method
        sb.append("    @Override\n");
        sb.append("    public Class<").append(recordSimpleName).append("> type() {\n");
        sb.append("        return ").append(recordSimpleName).append(".class;\n");
        sb.append("    }\n");

        // Helper methods for list conversion
        boolean needsListHelper = components.stream().anyMatch(c ->
                !c.ignored() && c.typeName().startsWith("java.util.List<"));
        if (needsListHelper) {
            sb.append("\n");
            sb.append("    @SuppressWarnings(\"unchecked\")\n");
            sb.append("    private static <E> java.util.List<E> _toList(JqValue value, JqMapper mapper, Class<E> elementType) {\n");
            sb.append("        if (value == null || value instanceof JqNull || !(value instanceof JqArray arr)) return java.util.List.of();\n");
            sb.append("        var kind = io.hyperfoil.tools.jjq.mapper.TypeConverter.resolveKind(elementType, elementType);\n");
            sb.append("        var list = new java.util.ArrayList<E>(arr.size());\n");
            sb.append("        for (JqValue elem : arr) {\n");
            sb.append("            list.add((E) io.hyperfoil.tools.jjq.mapper.TypeConverter.convert(\n");
            sb.append("                elem, kind, elementType, elementType, mapper));\n");
            sb.append("        }\n");
            sb.append("        return list;\n");
            sb.append("    }\n");
        }

        sb.append("}\n");
        return sb.toString();
    }

    private static void generateFromJqValue(StringBuilder sb, String recordSimpleName,
                                             List<JqMapperProcessor.ComponentInfo> components) {
        sb.append("    @Override\n");
        sb.append("    public ").append(recordSimpleName).append(" fromJqValue(JqValue input, JqMapper mapper) {\n");
        sb.append("        return new ").append(recordSimpleName).append("(\n");

        for (int i = 0; i < components.size(); i++) {
            var comp = components.get(i);
            sb.append("            ");
            if (comp.ignored()) {
                sb.append(defaultLiteral(comp.typeName()));
            } else {
                generateExtraction(sb, comp);
            }
            if (i < components.size() - 1) sb.append(",");
            sb.append("\n");
        }

        sb.append("        );\n");
        sb.append("    }\n\n");
    }

    private static void generateExtraction(StringBuilder sb, JqMapperProcessor.ComponentInfo comp) {
        String program = "P_" + comp.name().toUpperCase();
        String apply = program + ".apply(input)";

        // Custom converter takes priority
        if (comp.converterClass() != null) {
            sb.append("(").append(comp.typeName()).append(") CONV_")
              .append(comp.name().toUpperCase()).append(".fromJqValue(").append(apply).append(")");
            return;
        }

        switch (comp.typeName()) {
            case "java.lang.String" -> sb.append(apply).append(".asString(null)");
            case "int" -> sb.append("(int) ").append(apply).append(".asLong(0)");
            case "java.lang.Integer" -> sb.append("(int) ").append(apply).append(".asLong(0)");
            case "long" -> sb.append(apply).append(".asLong(0)");
            case "java.lang.Long" -> sb.append(apply).append(".asLong(0)");
            case "double" -> sb.append(apply).append(".asDouble(0.0)");
            case "java.lang.Double" -> sb.append(apply).append(".asDouble(0.0)");
            case "float" -> sb.append("(float) ").append(apply).append(".asDouble(0.0)");
            case "java.lang.Float" -> sb.append("(float) ").append(apply).append(".asDouble(0.0)");
            case "boolean" -> sb.append(apply).append(".asBoolean(false)");
            case "java.lang.Boolean" -> sb.append(apply).append(".asBoolean(false)");
            case "short" -> sb.append("(short) ").append(apply).append(".asLong(0)");
            case "java.lang.Short" -> sb.append("(short) ").append(apply).append(".asLong(0)");
            case "byte" -> sb.append("(byte) ").append(apply).append(".asLong(0)");
            case "java.lang.Byte" -> sb.append("(byte) ").append(apply).append(".asLong(0)");
            case "char", "java.lang.Character" -> {
                sb.append(apply).append(" instanceof JqString _s && !_s.stringValue().isEmpty() ? _s.stringValue().charAt(0) : '\\0'");
            }
            case "java.math.BigDecimal" -> {
                sb.append(apply).append(" instanceof JqNumber _n ? _n.decimalValue() : null");
            }
            default -> {
                String typeName = comp.typeName();
                // JqValue or subtypes — passthrough
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    sb.append(apply);
                }
                // List<T> — delegate to mapper for element conversion
                else if (typeName.startsWith("java.util.List<")) {
                    String elementType = extractGenericArg(typeName);
                    sb.append("_toList(").append(apply).append(", mapper, ").append(elementType).append(".class)");
                }
                // Map<String, V> — delegate to mapper for value conversion
                else if (typeName.startsWith("java.util.Map<")) {
                    sb.append("io.hyperfoil.tools.jjq.mapper.TypeConverter.toJava(")
                      .append(apply).append(", java.util.Map.class, null, mapper)");
                }
                // Optional<T>
                else if (typeName.startsWith("java.util.Optional<")) {
                    String innerType = extractGenericArg(typeName);
                    sb.append(apply).append(" instanceof JqNull ? Optional.empty() : Optional.ofNullable(");
                    generateScalarConversion(sb, innerType, apply);
                    sb.append(")");
                }
                // Enum
                else if (typeName.contains(".") && !typeName.startsWith("java.")) {
                    // Assume it's a record or enum — delegate to mapper
                    sb.append("mapper.fromJqValue(").append(apply).append(", ").append(typeName).append(".class)");
                }
                else {
                    // Fallback — delegate to mapper
                    sb.append("mapper.fromJqValue(").append(apply).append(", ").append(typeName).append(".class)");
                }
            }
        }
    }

    private static void generateScalarConversion(StringBuilder sb, String typeName, String apply) {
        switch (typeName) {
            case "java.lang.String", "String" -> sb.append(apply).append(".asString(null)");
            case "java.lang.Integer", "Integer", "int" -> sb.append("(int) ").append(apply).append(".asLong(0)");
            case "java.lang.Long", "Long", "long" -> sb.append(apply).append(".asLong(0)");
            case "java.lang.Double", "Double", "double" -> sb.append(apply).append(".asDouble(0.0)");
            case "java.lang.Float", "Float", "float" -> sb.append("(float) ").append(apply).append(".asDouble(0.0)");
            case "java.lang.Boolean", "Boolean", "boolean" -> sb.append(apply).append(".asBoolean(false)");
            case "java.lang.Short", "Short", "short" -> sb.append("(short) ").append(apply).append(".asLong(0)");
            case "java.lang.Byte", "Byte", "byte" -> sb.append("(byte) ").append(apply).append(".asLong(0)");
            case "java.lang.Character", "Character", "char" ->
                sb.append(apply).append(" instanceof JqString _s && !_s.stringValue().isEmpty() ? _s.stringValue().charAt(0) : '\\0'");
            case "java.math.BigDecimal", "BigDecimal" ->
                sb.append(apply).append(" instanceof JqNumber _n ? _n.decimalValue() : null");
            default -> sb.append(apply).append(".toJavaObject()");
        }
    }

    private static void generateToJqValue(StringBuilder sb, String recordSimpleName,
                                            List<JqMapperProcessor.ComponentInfo> components) {
        int activeCount = (int) components.stream().filter(c -> !c.ignored()).count();
        boolean hasInclusion = components.stream()
                .anyMatch(c -> !c.ignored() && !"ALWAYS".equals(c.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public JqValue toJqValue(").append(recordSimpleName).append(" instance, JqMapper mapper) {\n");

        if (!hasInclusion) {
            // Fast path: no inclusion filtering, keys unique — use putUnchecked
            sb.append("        return JqObject.builder(").append(activeCount).append(")\n");
            for (var comp : components) {
                if (comp.ignored()) continue;
                sb.append("            .putUnchecked(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(")\n");
            }
            sb.append("            .build();\n");
        } else {
            // Inclusion filtering: conditional puts, keys still unique — use putUnchecked
            sb.append("        var _b = JqObject.builder(").append(activeCount).append(");\n");
            for (var comp : components) {
                if (comp.ignored()) continue;
                String accessor = "instance." + comp.name() + "()";
                if ("ALWAYS".equals(comp.inclusion())) {
                    sb.append("        _b.putUnchecked(\"").append(comp.jsonName()).append("\", ");
                    generateSerializationValue(sb, comp);
                    sb.append(");\n");
                } else {
                    generateInclusionCheck(sb, comp, accessor);
                }
            }
            sb.append("        return _b.build();\n");
        }

        sb.append("    }\n\n");
    }

    /** Generate an inclusion-conditional put for a record component. */
    private static void generateInclusionCheck(StringBuilder sb, JqMapperProcessor.ComponentInfo comp, String accessor) {
        String inclusion = comp.inclusion();
        switch (inclusion) {
            case "NON_NULL" -> {
                sb.append("        if (").append(accessor).append(" != null) ");
                sb.append("_b.putUnchecked(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
            case "NON_EMPTY" -> {
                String typeName = comp.typeName();
                if (typeName.equals("java.lang.String")) {
                    sb.append("        if (").append(accessor).append(" != null && !").append(accessor).append(".isEmpty()) ");
                } else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")
                        || typeName.startsWith("java.util.Set") || typeName.startsWith("java.util.Collection")) {
                    sb.append("        if (").append(accessor).append(" != null && !").append(accessor).append(".isEmpty()) ");
                } else {
                    sb.append("        if (").append(accessor).append(" != null) ");
                }
                sb.append("_b.putUnchecked(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
            case "NON_DEFAULT" -> {
                String typeName = comp.typeName();
                String check = switch (typeName) {
                    case "int", "long", "short", "byte" -> accessor + " != 0";
                    case "double", "float" -> accessor + " != 0.0";
                    case "boolean" -> accessor;
                    case "char" -> accessor + " != '\\0'";
                    default -> accessor + " != null";
                };
                sb.append("        if (").append(check).append(") ");
                sb.append("_b.putUnchecked(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
            default -> {
                // ALWAYS — no check
                sb.append("        _b.putUnchecked(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
        }
    }

    @SuppressWarnings("rawtypes")
    private static void generateSerializationValue(StringBuilder sb, JqMapperProcessor.ComponentInfo comp) {
        String accessor = "instance." + comp.name() + "()";

        // Custom converter takes priority
        if (comp.converterClass() != null) {
            sb.append("((io.hyperfoil.tools.jjq.mapper.ValueConverter) CONV_")
              .append(comp.name().toUpperCase()).append(").toJqValue(").append(accessor).append(")");
            return;
        }

        switch (comp.typeName()) {
            case "java.lang.String" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqString.of(").append(accessor).append(")");
            case "int" -> sb.append("(long) ").append(accessor);
            case "java.lang.Integer" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqNumber.of((long) ").append(accessor).append(")");
            case "long" -> sb.append(accessor);
            case "java.lang.Long" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqNumber.of(").append(accessor).append(")");
            case "double" -> sb.append(accessor);
            case "java.lang.Double" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqNumber.of(").append(accessor).append(")");
            case "float" -> sb.append("(double) ").append(accessor);
            case "java.lang.Float" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqNumber.of((double) ").append(accessor).append(")");
            case "boolean" -> sb.append(accessor);
            case "java.lang.Boolean" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqBoolean.of(").append(accessor).append(")");
            case "short" -> sb.append("(long) ").append(accessor);
            case "java.lang.Short" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqNumber.of((long) ").append(accessor).append(")");
            case "byte" -> sb.append("(long) ").append(accessor);
            case "java.lang.Byte" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqNumber.of((long) ").append(accessor).append(")");
            case "char" -> sb.append("JqString.of(String.valueOf(").append(accessor).append("))");
            case "java.lang.Character" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqString.of(String.valueOf(").append(accessor).append("))");
            case "java.math.BigDecimal" ->
                sb.append(accessor).append(" == null ? JqNull.NULL : JqNumber.of(").append(accessor).append(")");
            default -> {
                String typeName = comp.typeName();
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    sb.append(accessor);
                } else {
                    // Records, Lists, Maps, Optionals, Enums — delegate to mapper's TypeConverter
                    sb.append("io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                      .append(accessor).append(", mapper)");
                }
            }
        }
    }

    /**
     * Generate the appendJson method — direct field-to-JSON serialization
     * that bypasses intermediate JqValue tree construction.
     */
    private static void generateAppendJson(StringBuilder sb, String recordSimpleName,
                                            List<JqMapperProcessor.ComponentInfo> components) {
        boolean hasInclusion = components.stream()
                .anyMatch(c -> !c.ignored() && !"ALWAYS".equals(c.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public void appendJson(").append(recordSimpleName)
          .append(" instance, StringBuilder _sb, JqMapper mapper) {\n");
        sb.append("        _sb.append('{');\n");

        if (!hasInclusion) {
            // No inclusion filtering — all fields always present, known separator positions
            boolean first = true;
            for (var comp : components) {
                if (comp.ignored()) continue;
                if (!first) sb.append("        _sb.append(',');\n");
                appendJsonField(sb, comp);
                first = false;
            }
        } else {
            // Inclusion filtering — need a separator flag
            sb.append("        boolean _sep = false;\n");
            for (var comp : components) {
                if (comp.ignored()) continue;
                String accessor = "instance." + comp.name() + "()";
                if ("ALWAYS".equals(comp.inclusion())) {
                    sb.append("        if (_sep) _sb.append(','); _sep = true;\n");
                    appendJsonField(sb, comp);
                } else {
                    appendJsonFieldWithInclusion(sb, comp, accessor);
                }
            }
        }

        sb.append("        _sb.append('}');\n");
        sb.append("    }\n\n");
    }

    /** Append a single field as JSON key:value to the StringBuilder. */
    private static void appendJsonField(StringBuilder sb, JqMapperProcessor.ComponentInfo comp) {
        String accessor = "instance." + comp.name() + "()";
        // Key — pre-escaped literal since JSON keys from Java identifiers never need escaping
        sb.append("        _sb.append(\"\\\"").append(escapeJava(comp.jsonName())).append("\\\":\");\n");
        // Value
        appendJsonValue(sb, comp, accessor);
    }

    /** Append a field with inclusion check. */
    private static void appendJsonFieldWithInclusion(StringBuilder sb,
                                                      JqMapperProcessor.ComponentInfo comp, String accessor) {
        String inclusion = comp.inclusion();
        String condition = switch (inclusion) {
            case "NON_NULL" -> accessor + " != null";
            case "NON_EMPTY" -> {
                String typeName = comp.typeName();
                if (typeName.equals("java.lang.String"))
                    yield accessor + " != null && !" + accessor + ".isEmpty()";
                else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")
                        || typeName.startsWith("java.util.Set") || typeName.startsWith("java.util.Collection"))
                    yield accessor + " != null && !" + accessor + ".isEmpty()";
                else
                    yield accessor + " != null";
            }
            case "NON_DEFAULT" -> switch (comp.typeName()) {
                case "int", "long", "short", "byte" -> accessor + " != 0";
                case "double", "float" -> accessor + " != 0.0";
                case "boolean" -> accessor;
                case "char" -> accessor + " != '\\0'";
                default -> accessor + " != null";
            };
            default -> "true";
        };
        sb.append("        if (").append(condition).append(") {\n");
        sb.append("            if (_sep) _sb.append(','); _sep = true;\n");
        sb.append("            _sb.append(\"\\\"").append(escapeJava(comp.jsonName())).append("\\\":\");\n");
        sb.append("    ");
        appendJsonValue(sb, comp, accessor);
        sb.append("        }\n");
    }

    /** Append the JSON value for a single field. */
    private static void appendJsonValue(StringBuilder sb, JqMapperProcessor.ComponentInfo comp, String accessor) {
        // Custom converter — must go through JqValue (null-safe via appendJqValue)
        if (comp.converterClass() != null) {
            sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJqValue(_sb, ((io.hyperfoil.tools.jjq.mapper.ValueConverter) CONV_")
              .append(comp.name().toUpperCase()).append(").toJqValue(").append(accessor).append("));\n");
            return;
        }

        switch (comp.typeName()) {
            case "java.lang.String", "char", "java.lang.Character" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_sb, ").append(accessor).append(");\n");
            case "int", "java.lang.Integer" ->
                sb.append("        _sb.append(").append(accessor).append(");\n");
            case "long", "java.lang.Long" ->
                sb.append("        _sb.append(").append(accessor).append(");\n");
            case "double", "java.lang.Double", "float", "java.lang.Float" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDouble(_sb, ").append(accessor).append(");\n");
            case "boolean", "java.lang.Boolean" ->
                sb.append("        _sb.append(").append(accessor).append(");\n");
            case "short", "java.lang.Short" ->
                sb.append("        _sb.append(").append(accessor).append(");\n");
            case "byte", "java.lang.Byte" ->
                sb.append("        _sb.append(").append(accessor).append(");\n");
            case "java.math.BigDecimal" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDecimal(_sb, ").append(accessor).append(");\n");
            default -> {
                String typeName = comp.typeName();
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    // JqValue — null-safe via appendJqValue
                    sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJqValue(_sb, ").append(accessor).append(");\n");
                } else {
                    // Complex types (records, enums, lists, maps, optionals) —
                    // fall back to TypeConverter for now
                    sb.append("        io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                      .append(accessor).append(", mapper).appendTo(_sb);\n");
                }
            }
        }
    }

    /**
     * Generate the appendJsonBytes method — direct field-to-bytes serialization
     * that bypasses intermediate JqValue tree construction.
     */
    private static void generateAppendJsonBytes(StringBuilder sb, String recordSimpleName,
                                                List<JqMapperProcessor.ComponentInfo> components) {
        boolean hasInclusion = components.stream()
                .anyMatch(c -> !c.ignored() && !"ALWAYS".equals(c.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public void appendJsonBytes(").append(recordSimpleName)
          .append(" instance, io.hyperfoil.tools.jjq.value.BytOutput _out, JqMapper mapper) {\n");
        sb.append("        _out.writeByte('{');\n");

        if (!hasInclusion) {
            boolean first = true;
            for (var comp : components) {
                if (comp.ignored()) continue;
                if (!first) sb.append("        _out.writeByte(',');\n");
                appendJsonBytesField(sb, comp);
                first = false;
            }
        } else {
            sb.append("        boolean _sep = false;\n");
            for (var comp : components) {
                if (comp.ignored()) continue;
                String accessor = "instance." + comp.name() + "()";
                if ("ALWAYS".equals(comp.inclusion())) {
                    sb.append("        if (_sep) _out.writeByte(','); _sep = true;\n");
                    appendJsonBytesField(sb, comp);
                } else {
                    appendJsonBytesFieldWithInclusion(sb, comp, accessor);
                }
            }
        }

        sb.append("        _out.writeByte('}');\n");
        sb.append("    }\n\n");
    }

    /** Append a single field as JSON key:value bytes. */
    private static void appendJsonBytesField(StringBuilder sb, JqMapperProcessor.ComponentInfo comp) {
        String accessor = "instance." + comp.name() + "()";
        sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_out, \"").append(escapeJava(comp.jsonName())).append("\");\n");
        sb.append("        _out.writeByte(':');\n");
        appendJsonBytesValue(sb, comp, accessor);
    }

    /** Append a field with inclusion check as bytes. */
    private static void appendJsonBytesFieldWithInclusion(StringBuilder sb,
                                                           JqMapperProcessor.ComponentInfo comp, String accessor) {
        String inclusion = comp.inclusion();
        String condition = switch (inclusion) {
            case "NON_NULL" -> accessor + " != null";
            case "NON_EMPTY" -> {
                String typeName = comp.typeName();
                if (typeName.equals("java.lang.String"))
                    yield accessor + " != null && !" + accessor + ".isEmpty()";
                else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")
                        || typeName.startsWith("java.util.Set") || typeName.startsWith("java.util.Collection"))
                    yield accessor + " != null && !" + accessor + ".isEmpty()";
                else
                    yield accessor + " != null";
            }
            case "NON_DEFAULT" -> switch (comp.typeName()) {
                case "int", "long", "short", "byte" -> accessor + " != 0";
                case "double", "float" -> accessor + " != 0.0";
                case "boolean" -> accessor;
                case "char" -> accessor + " != '\\0'";
                default -> accessor + " != null";
            };
            default -> "true";
        };
        sb.append("        if (").append(condition).append(") {\n");
        sb.append("            if (_sep) _out.writeByte(','); _sep = true;\n");
        sb.append("            io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_out, \"").append(escapeJava(comp.jsonName())).append("\");\n");
        sb.append("            _out.writeByte(':');\n");
        sb.append("    ");
        appendJsonBytesValue(sb, comp, accessor);
        sb.append("        }\n");
    }

    /** Append the JSON bytes for a single field value. */
    private static void appendJsonBytesValue(StringBuilder sb, JqMapperProcessor.ComponentInfo comp, String accessor) {
        // Custom converter — must go through JqValue (null-safe via appendJqValue)
        if (comp.converterClass() != null) {
            sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJqValue(_out, ((io.hyperfoil.tools.jjq.mapper.ValueConverter) CONV_")
              .append(comp.name().toUpperCase()).append(").toJqValue(").append(accessor).append("));\n");
            return;
        }

        switch (comp.typeName()) {
            case "java.lang.String", "char", "java.lang.Character" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_out, ").append(accessor).append(");\n");
            case "int", "long", "short", "byte" ->
                sb.append("        _out.writeLong(").append(accessor).append(");\n");
            case "java.lang.Integer", "java.lang.Long", "java.lang.Short", "java.lang.Byte" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonLong(_out, ").append(accessor).append(");\n");
            case "double", "float" ->
                sb.append("        _out.writeDouble((double) ").append(accessor).append(");\n");
            case "java.lang.Double", "java.lang.Float" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDouble(_out, ").append(accessor).append(");\n");
            case "boolean" ->
                sb.append("        if (").append(accessor).append(") _out.writeTrue(); else _out.writeFalse();\n");
            case "java.lang.Boolean" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonBoolean(_out, ").append(accessor).append(");\n");
            case "java.math.BigDecimal" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDecimal(_out, ").append(accessor).append(");\n");
            default -> {
                String typeName = comp.typeName();
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJqValue(_out, ").append(accessor).append(");\n");
                } else {
                    sb.append("        io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                      .append(accessor).append(", mapper).appendToBytes(_out);\n");
                }
            }
        }
    }

    /** Escape a string for use in a Java string literal. */
    private static String escapeJava(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
    }

    /** Return the Java default value literal for a type name. */
    private static String defaultLiteral(String typeName) {
        return switch (typeName) {
            case "int", "java.lang.Integer" -> "0";
            case "long", "java.lang.Long" -> "0L";
            case "double", "java.lang.Double" -> "0.0";
            case "float", "java.lang.Float" -> "0.0f";
            case "boolean", "java.lang.Boolean" -> "false";
            case "short", "java.lang.Short" -> "(short) 0";
            case "byte", "java.lang.Byte" -> "(byte) 0";
            case "char", "java.lang.Character" -> "'\\0'";
            default -> "null";
        };
    }

    /** Extract the first generic type argument from a parameterized type string like "java.util.List<java.lang.String>". */
    private static String extractGenericArg(String typeName) {
        int start = typeName.indexOf('<');
        int end = typeName.lastIndexOf('>');
        if (start >= 0 && end > start) {
            return typeName.substring(start + 1, end);
        }
        return "java.lang.Object";
    }

    /**
     * Generate the complete Java source for a POJO _JqMapping class.
     * Uses no-arg constructor + setter calls for deserialization,
     * and getter calls for serialization.
     */
    static String generateForClass(String packageName, String classSimpleName, String classQualifiedName,
                                    String mappingClassName, List<JqMapperProcessor.PropertyInfo> properties) {
        var sb = new StringBuilder(1024);

        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        // POJOs always use JqProgram for field access (interning advantage, see issue #76)
        boolean needsJqProgram = properties.stream().anyMatch(p -> !p.ignored());

        if (needsJqProgram) sb.append("import io.hyperfoil.tools.jjq.JqProgram;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.GeneratedMapping;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.JqMapper;\n");
        sb.append("import io.hyperfoil.tools.jjq.value.*;\n\n");

        sb.append("/**\n");
        sb.append(" * Generated mapping for {@link ").append(classQualifiedName).append("}.\n");
        sb.append(" * Do not edit — regenerated by jjq-mapper-processor.\n");
        sb.append(" */\n");
        sb.append("public final class ").append(mappingClassName);
        sb.append(" extends GeneratedMapping<").append(classSimpleName).append("> {\n\n");

        // Static JqProgram fields for all non-ignored fields (interning advantage)
        for (var prop : properties) {
            if (!prop.ignored()) {
                sb.append("    private static final JqProgram P_")
                  .append(prop.name().toUpperCase())
                  .append(" = JqProgram.compile(\"")
                  .append(escapeJava(prop.jqExpr()))
                  .append("\");\n");
            }
        }
        sb.append("\n");

        // fromJqValue: no-arg constructor + setters
        sb.append("    @Override\n");
        sb.append("    public ").append(classSimpleName).append(" fromJqValue(JqValue input, JqMapper mapper) {\n");
        sb.append("        ").append(classSimpleName).append(" instance = new ").append(classSimpleName).append("();\n");

        for (var prop : properties) {
            if (prop.ignored()) continue;
            String apply = "P_" + prop.name().toUpperCase() + ".apply(input)";
            String writeExpr = buildExtraction(prop.typeName(), apply);

            if (prop.isPublicField() && prop.setterName() == null) {
                // Direct public field write
                sb.append("        instance.").append(prop.name()).append(" = ").append(writeExpr).append(";\n");
            } else if (prop.setterName() != null) {
                // Setter method
                sb.append("        instance.").append(prop.setterName()).append("(").append(writeExpr).append(");\n");
            }
            // else: no setter and not public — skip (read-only at runtime via setAccessible)
        }

        sb.append("        return instance;\n");
        sb.append("    }\n\n");

        // toJqValue: getter calls
        int activeCount = (int) properties.stream().filter(p -> !p.ignored()).count();
        boolean hasInclusion = properties.stream()
                .anyMatch(p -> !p.ignored() && !"ALWAYS".equals(p.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public JqValue toJqValue(").append(classSimpleName).append(" instance, JqMapper mapper) {\n");

        if (!hasInclusion) {
            // Fast path: no inclusion filtering
            sb.append("        return JqObject.builder(").append(activeCount).append(")\n");
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                sb.append("            .putUnchecked(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(")\n");
            }
            sb.append("            .build();\n");
        } else {
            // Inclusion filtering: keys unique — use putUnchecked
            sb.append("        var _b = JqObject.builder(").append(activeCount).append(");\n");
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                if ("ALWAYS".equals(prop.inclusion())) {
                    sb.append("        _b.putUnchecked(\"").append(prop.jsonName()).append("\", ");
                    generateSerializationValueForPojo(sb, prop, readExpr);
                    sb.append(");\n");
                } else {
                    generatePojoInclusionCheck(sb, prop, readExpr);
                }
            }
            sb.append("        return _b.build();\n");
        }

        sb.append("    }\n\n");

        // appendJson — direct-to-JSON, bypasses JqValue tree
        generateAppendJsonForPojo(sb, classSimpleName, properties);

        // appendJsonBytes — direct-to-bytes, bypasses JqValue tree
        generateAppendJsonBytesForPojo(sb, classSimpleName, properties);

        // type()
        sb.append("    @Override\n");
        sb.append("    public Class<").append(classSimpleName).append("> type() {\n");
        sb.append("        return ").append(classSimpleName).append(".class;\n");
        sb.append("    }\n");

        sb.append("}\n");
        return sb.toString();
    }

    /**
     * Generate appendJson for POJOs — same pattern as records but uses getter/field access.
     */
    private static void generateAppendJsonForPojo(StringBuilder sb, String classSimpleName,
                                                   List<JqMapperProcessor.PropertyInfo> properties) {
        boolean hasInclusion = properties.stream()
                .anyMatch(p -> !p.ignored() && !"ALWAYS".equals(p.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public void appendJson(").append(classSimpleName)
          .append(" instance, StringBuilder _sb, JqMapper mapper) {\n");
        sb.append("        _sb.append('{');\n");

        if (!hasInclusion) {
            boolean first = true;
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                if (!first) sb.append("        _sb.append(',');\n");
                sb.append("        _sb.append(\"\\\"").append(escapeJava(prop.jsonName())).append("\\\":\");\n");
                appendJsonValueForPojo(sb, prop, readExpr);
                first = false;
            }
        } else {
            sb.append("        boolean _sep = false;\n");
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                if ("ALWAYS".equals(prop.inclusion())) {
                    sb.append("        if (_sep) _sb.append(','); _sep = true;\n");
                    sb.append("        _sb.append(\"\\\"").append(escapeJava(prop.jsonName())).append("\\\":\");\n");
                    appendJsonValueForPojo(sb, prop, readExpr);
                } else {
                    appendJsonFieldWithInclusionForPojo(sb, prop, readExpr);
                }
            }
        }

        sb.append("        _sb.append('}');\n");
        sb.append("    }\n\n");
    }

    /**
     * Generate appendJsonBytes for POJOs — same pattern as records but uses getter/field access.
     */
    private static void generateAppendJsonBytesForPojo(StringBuilder sb, String classSimpleName,
                                                        List<JqMapperProcessor.PropertyInfo> properties) {
        boolean hasInclusion = properties.stream()
                .anyMatch(p -> !p.ignored() && !"ALWAYS".equals(p.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public void appendJsonBytes(").append(classSimpleName)
          .append(" instance, io.hyperfoil.tools.jjq.value.BytOutput _out, JqMapper mapper) {\n");
        sb.append("        _out.writeByte('{');\n");

        if (!hasInclusion) {
            boolean first = true;
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                if (!first) sb.append("        _out.writeByte(',');\n");
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_out, \"").append(escapeJava(prop.jsonName())).append("\");\n");
                sb.append("        _out.writeByte(':');\n");
                appendJsonBytesValueForPojo(sb, prop, readExpr);
                first = false;
            }
        } else {
            sb.append("        boolean _sep = false;\n");
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                if ("ALWAYS".equals(prop.inclusion())) {
                    sb.append("        if (_sep) _out.writeByte(','); _sep = true;\n");
                    sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_out, \"").append(escapeJava(prop.jsonName())).append("\");\n");
                    sb.append("        _out.writeByte(':');\n");
                    appendJsonBytesValueForPojo(sb, prop, readExpr);
                } else {
                    appendJsonBytesFieldWithInclusionForPojo(sb, prop, readExpr);
                }
            }
        }

        sb.append("        _out.writeByte('}');\n");
        sb.append("    }\n\n");
    }

    /** Append JSON bytes for a POJO field value. */
    private static void appendJsonBytesValueForPojo(StringBuilder sb,
                                                     JqMapperProcessor.PropertyInfo prop, String readExpr) {
        switch (prop.typeName()) {
            case "java.lang.String", "char", "java.lang.Character" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_out, ").append(readExpr).append(");\n");
            case "int", "long", "short", "byte" ->
                sb.append("        _out.writeLong(").append(readExpr).append(");\n");
            case "java.lang.Integer", "java.lang.Long", "java.lang.Short", "java.lang.Byte" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonLong(_out, ").append(readExpr).append(");\n");
            case "double", "float" ->
                sb.append("        _out.writeDouble((double) ").append(readExpr).append(");\n");
            case "java.lang.Double", "java.lang.Float" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDouble(_out, ").append(readExpr).append(");\n");
            case "boolean" ->
                sb.append("        if (").append(readExpr).append(") _out.writeTrue(); else _out.writeFalse();\n");
            case "java.lang.Boolean" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonBoolean(_out, ").append(readExpr).append(");\n");
            case "java.math.BigDecimal" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDecimal(_out, ").append(readExpr).append(");\n");
            default -> {
                String typeName = prop.typeName();
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJqValue(_out, ").append(readExpr).append(");\n");
                } else {
                    sb.append("        io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                      .append(readExpr).append(", mapper).appendToBytes(_out);\n");
                }
            }
        }
    }

    /** Append a POJO field with inclusion check as bytes. */
    private static void appendJsonBytesFieldWithInclusionForPojo(StringBuilder sb,
                                                                  JqMapperProcessor.PropertyInfo prop, String readExpr) {
        String inclusion = prop.inclusion();
        String condition = switch (inclusion) {
            case "NON_NULL" -> readExpr + " != null";
            case "NON_EMPTY" -> {
                String typeName = prop.typeName();
                if (typeName.equals("java.lang.String"))
                    yield readExpr + " != null && !" + readExpr + ".isEmpty()";
                else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")
                        || typeName.startsWith("java.util.Set") || typeName.startsWith("java.util.Collection"))
                    yield readExpr + " != null && !" + readExpr + ".isEmpty()";
                else
                    yield readExpr + " != null";
            }
            case "NON_DEFAULT" -> switch (prop.typeName()) {
                case "int", "long", "short", "byte" -> readExpr + " != 0";
                case "double", "float" -> readExpr + " != 0.0";
                case "boolean" -> readExpr;
                case "char" -> readExpr + " != '\\0'";
                default -> readExpr + " != null";
            };
            default -> "true";
        };
        sb.append("        if (").append(condition).append(") {\n");
        sb.append("            if (_sep) _out.writeByte(','); _sep = true;\n");
        sb.append("            io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_out, \"").append(escapeJava(prop.jsonName())).append("\");\n");
        sb.append("            _out.writeByte(':');\n");
        sb.append("    ");
        appendJsonBytesValueForPojo(sb, prop, readExpr);
        sb.append("        }\n");
    }

    /** Append JSON value for a POJO field. */
    private static void appendJsonValueForPojo(StringBuilder sb,
                                                JqMapperProcessor.PropertyInfo prop, String readExpr) {
        switch (prop.typeName()) {
            case "java.lang.String", "char", "java.lang.Character" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonString(_sb, ").append(readExpr).append(");\n");
            case "int", "java.lang.Integer" ->
                sb.append("        _sb.append(").append(readExpr).append(");\n");
            case "long", "java.lang.Long" ->
                sb.append("        _sb.append(").append(readExpr).append(");\n");
            case "double", "java.lang.Double", "float", "java.lang.Float" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDouble(_sb, ").append(readExpr).append(");\n");
            case "boolean", "java.lang.Boolean" ->
                sb.append("        _sb.append(").append(readExpr).append(");\n");
            case "short", "java.lang.Short" ->
                sb.append("        _sb.append(").append(readExpr).append(");\n");
            case "byte", "java.lang.Byte" ->
                sb.append("        _sb.append(").append(readExpr).append(");\n");
            case "java.math.BigDecimal" ->
                sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJsonDecimal(_sb, ").append(readExpr).append(");\n");
            default -> {
                String typeName = prop.typeName();
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    sb.append("        io.hyperfoil.tools.jjq.value.JqValues.appendJqValue(_sb, ").append(readExpr).append(");\n");
                } else {
                    sb.append("        io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                      .append(readExpr).append(", mapper).appendTo(_sb);\n");
                }
            }
        }
    }

    /** Append a POJO field with inclusion check in appendJson. */
    private static void appendJsonFieldWithInclusionForPojo(StringBuilder sb,
                                                             JqMapperProcessor.PropertyInfo prop, String readExpr) {
        String inclusion = prop.inclusion();
        String condition = switch (inclusion) {
            case "NON_NULL" -> readExpr + " != null";
            case "NON_EMPTY" -> {
                String typeName = prop.typeName();
                if (typeName.equals("java.lang.String"))
                    yield readExpr + " != null && !" + readExpr + ".isEmpty()";
                else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")
                        || typeName.startsWith("java.util.Set") || typeName.startsWith("java.util.Collection"))
                    yield readExpr + " != null && !" + readExpr + ".isEmpty()";
                else
                    yield readExpr + " != null";
            }
            case "NON_DEFAULT" -> switch (prop.typeName()) {
                case "int", "long", "short", "byte" -> readExpr + " != 0";
                case "double", "float" -> readExpr + " != 0.0";
                case "boolean" -> readExpr;
                case "char" -> readExpr + " != '\\0'";
                default -> readExpr + " != null";
            };
            default -> "true";
        };
        sb.append("        if (").append(condition).append(") {\n");
        sb.append("            if (_sep) _sb.append(','); _sep = true;\n");
        sb.append("            _sb.append(\"\\\"").append(escapeJava(prop.jsonName())).append("\\\":\");\n");
        sb.append("    ");
        appendJsonValueForPojo(sb, prop, readExpr);
        sb.append("        }\n");
    }

    /** Build a type-coerced extraction expression for a POJO field. */
    private static String buildExtraction(String typeName, String apply) {
        return switch (typeName) {
            case "java.lang.String" -> apply + ".asString(null)";
            case "int", "java.lang.Integer" -> "(int) " + apply + ".asLong(0)";
            case "long", "java.lang.Long" -> apply + ".asLong(0)";
            case "double", "java.lang.Double" -> apply + ".asDouble(0.0)";
            case "float", "java.lang.Float" -> "(float) " + apply + ".asDouble(0.0)";
            case "boolean", "java.lang.Boolean" -> apply + ".asBoolean(false)";
            case "short", "java.lang.Short" -> "(short) " + apply + ".asLong(0)";
            case "byte", "java.lang.Byte" -> "(byte) " + apply + ".asLong(0)";
            case "char", "java.lang.Character" ->
                apply + " instanceof JqString _s && !_s.stringValue().isEmpty() ? _s.stringValue().charAt(0) : '\\0'";
            case "java.math.BigDecimal" -> apply + " instanceof JqNumber _n ? _n.decimalValue() : null";
            default -> {
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue") || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    yield apply;
                }
                yield "mapper.fromJqValue(" + apply + ", " + typeName + ".class)";
            }
        };
    }

    /** Resolve read expression for a POJO field. Returns null if not accessible. */
    private static String resolvePojoReadExpr(JqMapperProcessor.PropertyInfo prop) {
        if (prop.isPublicField() && prop.getterName() == null) {
            return "instance." + prop.name();
        } else if (prop.getterName() != null) {
            return "instance." + prop.getterName() + "()";
        }
        return null; // not accessible in generated code
    }

    /** Generate an inclusion-conditional put for a POJO property. */
    private static void generatePojoInclusionCheck(StringBuilder sb,
                                                    JqMapperProcessor.PropertyInfo prop, String readExpr) {
        String inclusion = prop.inclusion();
        switch (inclusion) {
            case "NON_NULL" -> {
                sb.append("        if (").append(readExpr).append(" != null) ");
                sb.append("_b.putUnchecked(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
            case "NON_EMPTY" -> {
                String typeName = prop.typeName();
                if (typeName.equals("java.lang.String")) {
                    sb.append("        if (").append(readExpr).append(" != null && !").append(readExpr).append(".isEmpty()) ");
                } else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")
                        || typeName.startsWith("java.util.Set") || typeName.startsWith("java.util.Collection")) {
                    sb.append("        if (").append(readExpr).append(" != null && !").append(readExpr).append(".isEmpty()) ");
                } else {
                    sb.append("        if (").append(readExpr).append(" != null) ");
                }
                sb.append("_b.putUnchecked(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
            case "NON_DEFAULT" -> {
                String typeName = prop.typeName();
                String check = switch (typeName) {
                    case "int", "long", "short", "byte" -> readExpr + " != 0";
                    case "double", "float" -> readExpr + " != 0.0";
                    case "boolean" -> readExpr;
                    case "char" -> readExpr + " != '\\0'";
                    default -> readExpr + " != null";
                };
                sb.append("        if (").append(check).append(") ");
                sb.append("_b.putUnchecked(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
            default -> {
                sb.append("        _b.putUnchecked(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
        }
    }

    /** Generate the serialization value expression for a POJO field. */
    private static void generateSerializationValueForPojo(StringBuilder sb,
                                                           JqMapperProcessor.PropertyInfo prop, String readExpr) {
        switch (prop.typeName()) {
            case "java.lang.String" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqString.of(").append(readExpr).append(")");
            case "int" -> sb.append("(long) ").append(readExpr);
            case "java.lang.Integer" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqNumber.of((long) ").append(readExpr).append(")");
            case "long" -> sb.append(readExpr);
            case "java.lang.Long" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqNumber.of(").append(readExpr).append(")");
            case "double" -> sb.append(readExpr);
            case "java.lang.Double" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqNumber.of(").append(readExpr).append(")");
            case "float" -> sb.append("(double) ").append(readExpr);
            case "java.lang.Float" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqNumber.of((double) ").append(readExpr).append(")");
            case "boolean" -> sb.append(readExpr);
            case "java.lang.Boolean" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqBoolean.of(").append(readExpr).append(")");
            case "short" -> sb.append("(long) ").append(readExpr);
            case "java.lang.Short" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqNumber.of((long) ").append(readExpr).append(")");
            case "byte" -> sb.append("(long) ").append(readExpr);
            case "java.lang.Byte" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqNumber.of((long) ").append(readExpr).append(")");
            case "char" -> sb.append("JqString.of(String.valueOf(").append(readExpr).append("))");
            case "java.lang.Character" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqString.of(String.valueOf(").append(readExpr).append("))");
            case "java.math.BigDecimal" ->
                sb.append(readExpr).append(" == null ? JqNull.NULL : JqNumber.of(").append(readExpr).append(")");
            default -> sb.append("io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                         .append(readExpr).append(", mapper)");
        }
    }

    /**
     * Generate the Java source for a {@code JqMappingRegistry} class that
     * registers all generated mappings in a single method call.
     *
     * <p>Usage:</p>
     * <pre>{@code
     * JqMapper.Builder builder = JqMapper.builder();
     * JqMappingRegistry.registerAll(builder);
     * JqMapper mapper = builder.build();
     * }</pre>
     *
     * @param packageName        the package for the registry class
     * @param mappingClassNames  simple class names of generated mappings (e.g., "User_JqMapping")
     * @return the complete Java source for the registry class
     */
    static String generateRegistry(String packageName, List<String> mappingClassNames) {
        var sb = new StringBuilder(512);

        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        sb.append("import io.hyperfoil.tools.jjq.mapper.JqMapper;\n\n");

        sb.append("/**\n");
        sb.append(" * Generated registry for all {@code @JqMapped} records in this package.\n");
        sb.append(" * Do not edit — regenerated by jjq-mapper-processor.\n");
        sb.append(" *\n");
        sb.append(" * <p>Usage:</p>\n");
        sb.append(" * <pre>{@code\n");
        sb.append(" * JqMapper.Builder builder = JqMapper.builder();\n");
        sb.append(" * JqMappingRegistry.registerAll(builder);\n");
        sb.append(" * JqMapper mapper = builder.build();\n");
        sb.append(" * }</pre>\n");
        sb.append(" */\n");
        sb.append("public final class JqMappingRegistry {\n\n");
        sb.append("    private JqMappingRegistry() {}\n\n");
        sb.append("    /**\n");
        sb.append("     * Register all generated mappings from this package with the given builder.\n");
        sb.append("     *\n");
        sb.append("     * @param builder the mapper builder to register mappings with\n");
        sb.append("     */\n");
        sb.append("    public static void registerAll(JqMapper.Builder builder) {\n");

        for (String mappingClassName : mappingClassNames) {
            sb.append("        builder.register(new ").append(mappingClassName).append("());\n");
        }

        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }
}
