package io.hyperfoil.tools.jjq.mapper.processor;

import java.util.List;

/**
 * Generates Java source code for a record mapping class.
 * Uses raw StringBuilder — no code generation library dependency.
 *
 * <p>For records with more than {@value #HELPER_METHOD_THRESHOLD} non-ignored
 * components, field extractions are generated as separate {@code private static}
 * helper methods instead of being inlined into {@code fromJqValue()}. This gives
 * C2 the freedom to manage register pressure — on x86_64, inlining N extraction
 * calls into one method exhausts the 16 GP registers, causing register spills
 * (push/pop to stack). See issue #64.</p>
 */
final class MappingCodeGenerator {

    /**
     * Records with more than this many non-ignored components generate per-field
     * helper methods to avoid register spilling on x86_64.
     */
    static final int HELPER_METHOD_THRESHOLD = 8;

    private MappingCodeGenerator() {}

    /**
     * Generate the complete Java source for a _JqMapping class.
     */
    static String generate(String packageName, String recordSimpleName, String recordQualifiedName,
                           String mappingClassName, List<JqMapperProcessor.ComponentInfo> components) {
        var sb = new StringBuilder(1024);

        // Package declaration
        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        // Imports
        sb.append("import io.hyperfoil.tools.jjq.JqProgram;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.GeneratedMapping;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.JqMapper;\n");
        sb.append("import io.hyperfoil.tools.jjq.value.*;\n");
        sb.append("\n");
        // Additional imports for specific types
        boolean needsBigDecimal = components.stream().anyMatch(c -> c.typeName().equals("java.math.BigDecimal"));
        boolean needsList = components.stream().anyMatch(c -> c.typeName().startsWith("java.util.List"));
        boolean needsMap = components.stream().anyMatch(c -> c.typeName().startsWith("java.util.Map"));
        boolean needsOptional = components.stream().anyMatch(c -> c.typeName().startsWith("java.util.Optional"));
        boolean needsArrayList = needsList;

        if (needsBigDecimal) sb.append("import java.math.BigDecimal;\n");
        if (needsList) sb.append("import java.util.List;\n");
        if (needsArrayList) sb.append("import java.util.ArrayList;\n");
        if (needsMap) {
            sb.append("import java.util.Map;\n");
            sb.append("import java.util.LinkedHashMap;\n");
        }
        if (needsOptional) sb.append("import java.util.Optional;\n");
        if (needsBigDecimal || needsList || needsMap || needsOptional) sb.append("\n");

        // Class declaration
        sb.append("/**\n");
        sb.append(" * Generated mapping for {@link ").append(recordQualifiedName).append("}.\n");
        sb.append(" * Do not edit — regenerated by jjq-mapper-processor.\n");
        sb.append(" */\n");
        sb.append("public final class ").append(mappingClassName);
        sb.append(" extends GeneratedMapping<").append(recordSimpleName).append("> {\n\n");

        // Static JqProgram fields for each non-ignored component
        for (var comp : components) {
            if (!comp.ignored()) {
                sb.append("    private static final JqProgram P_")
                  .append(comp.name().toUpperCase())
                  .append(" = JqProgram.compile(\"")
                  .append(escapeJava(comp.jqExpr()))
                  .append("\");\n");
            }
        }
        sb.append("\n");

        // fromJqValue method
        generateFromJqValue(sb, recordSimpleName, components);

        // toJqValue method
        generateToJqValue(sb, recordSimpleName, components);

        // type() method
        sb.append("    @Override\n");
        sb.append("    public Class<").append(recordSimpleName).append("> type() {\n");
        sb.append("        return ").append(recordSimpleName).append(".class;\n");
        sb.append("    }\n");

        // Helper methods for list conversion
        boolean needsListHelper = components.stream().anyMatch(c ->
                !c.ignored() && c.typeName().startsWith("java.util.List<"));
        if (needsListHelper) {
            sb.append("\n");
            sb.append("    @SuppressWarnings(\"unchecked\")\n");
            sb.append("    private static <E> java.util.List<E> _toList(JqValue value, JqMapper mapper, Class<E> elementType) {\n");
            sb.append("        if (value == null || value instanceof JqNull || !(value instanceof JqArray arr)) return java.util.List.of();\n");
            sb.append("        var list = new java.util.ArrayList<E>(arr.size());\n");
            sb.append("        for (JqValue elem : arr) {\n");
            sb.append("            list.add((E) io.hyperfoil.tools.jjq.mapper.TypeConverter.convert(\n");
            sb.append("                elem, io.hyperfoil.tools.jjq.mapper.TypeConverter.resolveKind(elementType, elementType),\n");
            sb.append("                elementType, elementType, mapper));\n");
            sb.append("        }\n");
            sb.append("        return list;\n");
            sb.append("    }\n");
        }

        sb.append("}\n");
        return sb.toString();
    }

    private static void generateFromJqValue(StringBuilder sb, String recordSimpleName,
                                             List<JqMapperProcessor.ComponentInfo> components) {
        // All extractions are inlined into fromJqValue regardless of field count.
        // On x86_64 with >8 fields, C2 may spill registers (see issue #64 and
        // Franz Nigro's blog on Jackson register spilling). However, the generated
        // mapper is still faster than both reflection and Jackson up to ~25 fields.
        // For larger records, the reflection-based ClassMapping with forEach fast
        // path scales better — JqMapper falls back to it automatically when no
        // generated mapping exists.
        sb.append("    @Override\n");
        sb.append("    public ").append(recordSimpleName).append(" fromJqValue(JqValue input, JqMapper mapper) {\n");
        sb.append("        return new ").append(recordSimpleName).append("(\n");

        for (int i = 0; i < components.size(); i++) {
            var comp = components.get(i);
            sb.append("            ");
            if (comp.ignored()) {
                sb.append(defaultLiteral(comp.typeName()));
            } else {
                generateExtraction(sb, comp);
            }
            if (i < components.size() - 1) sb.append(",");
            sb.append("\n");
        }

        sb.append("        );\n");
        sb.append("    }\n\n");
    }

    private static void generateExtraction(StringBuilder sb, JqMapperProcessor.ComponentInfo comp) {
        String program = "P_" + comp.name().toUpperCase();
        String apply = program + ".apply(input)";

        switch (comp.typeName()) {
            case "java.lang.String" -> sb.append(apply).append(".asString(null)");
            case "int" -> sb.append("(int) ").append(apply).append(".asLong(0)");
            case "java.lang.Integer" -> sb.append("(int) ").append(apply).append(".asLong(0)");
            case "long" -> sb.append(apply).append(".asLong(0)");
            case "java.lang.Long" -> sb.append(apply).append(".asLong(0)");
            case "double" -> sb.append(apply).append(".asDouble(0.0)");
            case "java.lang.Double" -> sb.append(apply).append(".asDouble(0.0)");
            case "float" -> sb.append("(float) ").append(apply).append(".asDouble(0.0)");
            case "java.lang.Float" -> sb.append("(float) ").append(apply).append(".asDouble(0.0)");
            case "boolean" -> sb.append(apply).append(".asBoolean(false)");
            case "java.lang.Boolean" -> sb.append(apply).append(".asBoolean(false)");
            case "short" -> sb.append("(short) ").append(apply).append(".asLong(0)");
            case "java.lang.Short" -> sb.append("(short) ").append(apply).append(".asLong(0)");
            case "byte" -> sb.append("(byte) ").append(apply).append(".asLong(0)");
            case "java.lang.Byte" -> sb.append("(byte) ").append(apply).append(".asLong(0)");
            case "java.math.BigDecimal" -> {
                sb.append(apply).append(" instanceof JqNumber _n ? _n.decimalValue() : null");
            }
            default -> {
                String typeName = comp.typeName();
                // JqValue or subtypes — passthrough
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    sb.append(apply);
                }
                // List<T> — delegate to mapper for element conversion
                else if (typeName.startsWith("java.util.List<")) {
                    String elementType = extractGenericArg(typeName);
                    sb.append("_toList(").append(apply).append(", mapper, ").append(elementType).append(".class)");
                }
                // Map<String, V> — delegate to mapper for value conversion
                else if (typeName.startsWith("java.util.Map<")) {
                    sb.append("io.hyperfoil.tools.jjq.mapper.TypeConverter.toJava(")
                      .append(apply).append(", java.util.Map.class, null, mapper)");
                }
                // Optional<T>
                else if (typeName.startsWith("java.util.Optional<")) {
                    String innerType = extractGenericArg(typeName);
                    sb.append(apply).append(" instanceof JqNull ? Optional.empty() : Optional.ofNullable(");
                    generateScalarConversion(sb, innerType, apply);
                    sb.append(")");
                }
                // Enum
                else if (typeName.contains(".") && !typeName.startsWith("java.")) {
                    // Assume it's a record or enum — delegate to mapper
                    sb.append("mapper.fromJqValue(").append(apply).append(", ").append(typeName).append(".class)");
                }
                else {
                    // Fallback — delegate to mapper
                    sb.append("mapper.fromJqValue(").append(apply).append(", ").append(typeName).append(".class)");
                }
            }
        }
    }

    private static void generateScalarConversion(StringBuilder sb, String typeName, String apply) {
        switch (typeName) {
            case "java.lang.String", "String" -> sb.append(apply).append(".asString(null)");
            case "java.lang.Integer", "Integer", "int" -> sb.append("(int) ").append(apply).append(".asLong(0)");
            case "java.lang.Long", "Long", "long" -> sb.append(apply).append(".asLong(0)");
            case "java.lang.Double", "Double", "double" -> sb.append(apply).append(".asDouble(0.0)");
            case "java.lang.Boolean", "Boolean", "boolean" -> sb.append(apply).append(".asBoolean(false)");
            default -> sb.append(apply).append(".toJavaObject()");
        }
    }

    private static void generateToJqValue(StringBuilder sb, String recordSimpleName,
                                            List<JqMapperProcessor.ComponentInfo> components) {
        int activeCount = (int) components.stream().filter(c -> !c.ignored()).count();
        boolean hasInclusion = components.stream()
                .anyMatch(c -> !c.ignored() && !"ALWAYS".equals(c.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public JqValue toJqValue(").append(recordSimpleName).append(" instance, JqMapper mapper) {\n");

        if (!hasInclusion) {
            // Fast path: no inclusion filtering, use fluent builder
            sb.append("        return JqObject.builder(").append(activeCount).append(")\n");
            for (var comp : components) {
                if (comp.ignored()) continue;
                sb.append("            .put(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(")\n");
            }
            sb.append("            .build();\n");
        } else {
            // Inclusion filtering: use explicit builder with conditional puts
            sb.append("        var _b = JqObject.builder(").append(activeCount).append(");\n");
            for (var comp : components) {
                if (comp.ignored()) continue;
                String accessor = "instance." + comp.name() + "()";
                if ("ALWAYS".equals(comp.inclusion())) {
                    sb.append("        _b.put(\"").append(comp.jsonName()).append("\", ");
                    generateSerializationValue(sb, comp);
                    sb.append(");\n");
                } else {
                    generateInclusionCheck(sb, comp, accessor);
                }
            }
            sb.append("        return _b.build();\n");
        }

        sb.append("    }\n\n");
    }

    /** Generate an inclusion-conditional put for a record component. */
    private static void generateInclusionCheck(StringBuilder sb, JqMapperProcessor.ComponentInfo comp, String accessor) {
        String inclusion = comp.inclusion();
        switch (inclusion) {
            case "NON_NULL" -> {
                sb.append("        if (").append(accessor).append(" != null) ");
                sb.append("_b.put(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
            case "NON_EMPTY" -> {
                String typeName = comp.typeName();
                if (typeName.equals("java.lang.String")) {
                    sb.append("        if (").append(accessor).append(" != null && !").append(accessor).append(".isEmpty()) ");
                } else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")) {
                    sb.append("        if (").append(accessor).append(" != null && !").append(accessor).append(".isEmpty()) ");
                } else {
                    sb.append("        if (").append(accessor).append(" != null) ");
                }
                sb.append("_b.put(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
            case "NON_DEFAULT" -> {
                String typeName = comp.typeName();
                String check = switch (typeName) {
                    case "int", "long", "short", "byte" -> accessor + " != 0";
                    case "double", "float" -> accessor + " != 0.0";
                    case "boolean" -> accessor;
                    case "char" -> accessor + " != '\\0'";
                    default -> accessor + " != null";
                };
                sb.append("        if (").append(check).append(") ");
                sb.append("_b.put(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
            default -> {
                // ALWAYS — no check
                sb.append("        _b.put(\"").append(comp.jsonName()).append("\", ");
                generateSerializationValue(sb, comp);
                sb.append(");\n");
            }
        }
    }

    private static void generateSerializationValue(StringBuilder sb, JqMapperProcessor.ComponentInfo comp) {
        String accessor = "instance." + comp.name() + "()";

        switch (comp.typeName()) {
            case "java.lang.String" -> sb.append(accessor);
            case "int", "java.lang.Integer" -> sb.append("(long) ").append(accessor);
            case "long", "java.lang.Long" -> sb.append(accessor);
            case "double", "java.lang.Double" -> sb.append(accessor);
            case "float", "java.lang.Float" -> sb.append("(double) ").append(accessor);
            case "boolean", "java.lang.Boolean" -> sb.append(accessor);
            case "short", "java.lang.Short" -> sb.append("(long) ").append(accessor);
            case "byte", "java.lang.Byte" -> sb.append("(long) ").append(accessor);
            case "java.math.BigDecimal" -> sb.append("JqNumber.of(").append(accessor).append(")");
            default -> {
                String typeName = comp.typeName();
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue")
                    || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    sb.append(accessor);
                } else {
                    // Records, Lists, Maps, Optionals, Enums — delegate to mapper's TypeConverter
                    sb.append("io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                      .append(accessor).append(", mapper)");
                }
            }
        }
    }

    /** Escape a string for use in a Java string literal. */
    private static String escapeJava(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
    }

    /** Return the Java default value literal for a type name. */
    private static String defaultLiteral(String typeName) {
        return switch (typeName) {
            case "int", "java.lang.Integer" -> "0";
            case "long", "java.lang.Long" -> "0L";
            case "double", "java.lang.Double" -> "0.0";
            case "float", "java.lang.Float" -> "0.0f";
            case "boolean", "java.lang.Boolean" -> "false";
            case "short", "java.lang.Short" -> "(short) 0";
            case "byte", "java.lang.Byte" -> "(byte) 0";
            case "char", "java.lang.Character" -> "'\\0'";
            default -> "null";
        };
    }

    /** Extract the first generic type argument from a parameterized type string like "java.util.List<java.lang.String>". */
    private static String extractGenericArg(String typeName) {
        int start = typeName.indexOf('<');
        int end = typeName.lastIndexOf('>');
        if (start >= 0 && end > start) {
            return typeName.substring(start + 1, end);
        }
        return "java.lang.Object";
    }

    /**
     * Generate the complete Java source for a POJO _JqMapping class.
     * Uses no-arg constructor + setter calls for deserialization,
     * and getter calls for serialization.
     */
    static String generateForClass(String packageName, String classSimpleName, String classQualifiedName,
                                    String mappingClassName, List<JqMapperProcessor.PropertyInfo> properties) {
        var sb = new StringBuilder(1024);

        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        // POJOs always use JqProgram for field access (interning advantage, see issue #76)
        boolean needsJqProgram = properties.stream().anyMatch(p -> !p.ignored());

        if (needsJqProgram) sb.append("import io.hyperfoil.tools.jjq.JqProgram;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.GeneratedMapping;\n");
        sb.append("import io.hyperfoil.tools.jjq.mapper.JqMapper;\n");
        sb.append("import io.hyperfoil.tools.jjq.value.*;\n\n");

        sb.append("/**\n");
        sb.append(" * Generated mapping for {@link ").append(classQualifiedName).append("}.\n");
        sb.append(" * Do not edit — regenerated by jjq-mapper-processor.\n");
        sb.append(" */\n");
        sb.append("public final class ").append(mappingClassName);
        sb.append(" extends GeneratedMapping<").append(classSimpleName).append("> {\n\n");

        // Static JqProgram fields for all non-ignored fields (interning advantage)
        for (var prop : properties) {
            if (!prop.ignored()) {
                sb.append("    private static final JqProgram P_")
                  .append(prop.name().toUpperCase())
                  .append(" = JqProgram.compile(\"")
                  .append(escapeJava(prop.jqExpr()))
                  .append("\");\n");
            }
        }
        sb.append("\n");

        // fromJqValue: no-arg constructor + setters
        sb.append("    @Override\n");
        sb.append("    public ").append(classSimpleName).append(" fromJqValue(JqValue input, JqMapper mapper) {\n");
        sb.append("        ").append(classSimpleName).append(" instance = new ").append(classSimpleName).append("();\n");

        for (var prop : properties) {
            if (prop.ignored()) continue;
            String apply = "P_" + prop.name().toUpperCase() + ".apply(input)";
            String writeExpr = buildExtraction(prop.typeName(), apply);

            if (prop.isPublicField() && prop.setterName() == null) {
                // Direct public field write
                sb.append("        instance.").append(prop.name()).append(" = ").append(writeExpr).append(";\n");
            } else if (prop.setterName() != null) {
                // Setter method
                sb.append("        instance.").append(prop.setterName()).append("(").append(writeExpr).append(");\n");
            }
            // else: no setter and not public — skip (read-only at runtime via setAccessible)
        }

        sb.append("        return instance;\n");
        sb.append("    }\n\n");

        // toJqValue: getter calls
        int activeCount = (int) properties.stream().filter(p -> !p.ignored()).count();
        boolean hasInclusion = properties.stream()
                .anyMatch(p -> !p.ignored() && !"ALWAYS".equals(p.inclusion()));

        sb.append("    @Override\n");
        sb.append("    public JqValue toJqValue(").append(classSimpleName).append(" instance, JqMapper mapper) {\n");

        if (!hasInclusion) {
            // Fast path: no inclusion filtering
            sb.append("        return JqObject.builder(").append(activeCount).append(")\n");
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                sb.append("            .put(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(")\n");
            }
            sb.append("            .build();\n");
        } else {
            // Inclusion filtering: explicit builder with conditional puts
            sb.append("        var _b = JqObject.builder(").append(activeCount).append(");\n");
            for (var prop : properties) {
                if (prop.ignored()) continue;
                String readExpr = resolvePojoReadExpr(prop);
                if (readExpr == null) continue;
                if ("ALWAYS".equals(prop.inclusion())) {
                    sb.append("        _b.put(\"").append(prop.jsonName()).append("\", ");
                    generateSerializationValueForPojo(sb, prop, readExpr);
                    sb.append(");\n");
                } else {
                    generatePojoInclusionCheck(sb, prop, readExpr);
                }
            }
            sb.append("        return _b.build();\n");
        }

        sb.append("    }\n\n");

        // type()
        sb.append("    @Override\n");
        sb.append("    public Class<").append(classSimpleName).append("> type() {\n");
        sb.append("        return ").append(classSimpleName).append(".class;\n");
        sb.append("    }\n");

        sb.append("}\n");

        // Wait — the generated fromJqValue uses P_*.apply() but we need to also generate
        // the static fields for simple field accesses. Let me fix: for POJOs in generated code,
        // we always use JqProgram since it has the interning advantage.
        return sb.toString();
    }

    /** Build a type-coerced extraction expression for a POJO field. */
    private static String buildExtraction(String typeName, String apply) {
        return switch (typeName) {
            case "java.lang.String" -> apply + ".asString(null)";
            case "int", "java.lang.Integer" -> "(int) " + apply + ".asLong(0)";
            case "long", "java.lang.Long" -> apply + ".asLong(0)";
            case "double", "java.lang.Double" -> apply + ".asDouble(0.0)";
            case "float", "java.lang.Float" -> "(float) " + apply + ".asDouble(0.0)";
            case "boolean", "java.lang.Boolean" -> apply + ".asBoolean(false)";
            case "short", "java.lang.Short" -> "(short) " + apply + ".asLong(0)";
            case "byte", "java.lang.Byte" -> "(byte) " + apply + ".asLong(0)";
            case "java.math.BigDecimal" -> apply + " instanceof JqNumber _n ? _n.decimalValue() : null";
            default -> {
                if (typeName.equals("io.hyperfoil.tools.jjq.value.JqValue") || typeName.equals("JqValue")
                    || typeName.startsWith("io.hyperfoil.tools.jjq.value.Jq")) {
                    yield apply;
                }
                yield "mapper.fromJqValue(" + apply + ", " + typeName + ".class)";
            }
        };
    }

    /** Resolve read expression for a POJO field. Returns null if not accessible. */
    private static String resolvePojoReadExpr(JqMapperProcessor.PropertyInfo prop) {
        if (prop.isPublicField() && prop.getterName() == null) {
            return "instance." + prop.name();
        } else if (prop.getterName() != null) {
            return "instance." + prop.getterName() + "()";
        }
        return null; // not accessible in generated code
    }

    /** Generate an inclusion-conditional put for a POJO property. */
    private static void generatePojoInclusionCheck(StringBuilder sb,
                                                    JqMapperProcessor.PropertyInfo prop, String readExpr) {
        String inclusion = prop.inclusion();
        switch (inclusion) {
            case "NON_NULL" -> {
                sb.append("        if (").append(readExpr).append(" != null) ");
                sb.append("_b.put(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
            case "NON_EMPTY" -> {
                String typeName = prop.typeName();
                if (typeName.equals("java.lang.String")) {
                    sb.append("        if (").append(readExpr).append(" != null && !").append(readExpr).append(".isEmpty()) ");
                } else if (typeName.startsWith("java.util.List") || typeName.startsWith("java.util.Map")) {
                    sb.append("        if (").append(readExpr).append(" != null && !").append(readExpr).append(".isEmpty()) ");
                } else {
                    sb.append("        if (").append(readExpr).append(" != null) ");
                }
                sb.append("_b.put(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
            case "NON_DEFAULT" -> {
                String typeName = prop.typeName();
                String check = switch (typeName) {
                    case "int", "long", "short", "byte" -> readExpr + " != 0";
                    case "double", "float" -> readExpr + " != 0.0";
                    case "boolean" -> readExpr;
                    case "char" -> readExpr + " != '\\0'";
                    default -> readExpr + " != null";
                };
                sb.append("        if (").append(check).append(") ");
                sb.append("_b.put(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
            default -> {
                sb.append("        _b.put(\"").append(prop.jsonName()).append("\", ");
                generateSerializationValueForPojo(sb, prop, readExpr);
                sb.append(");\n");
            }
        }
    }

    /** Generate the serialization value expression for a POJO field. */
    private static void generateSerializationValueForPojo(StringBuilder sb,
                                                           JqMapperProcessor.PropertyInfo prop, String readExpr) {
        switch (prop.typeName()) {
            case "java.lang.String" -> sb.append(readExpr);
            case "int", "java.lang.Integer" -> sb.append("(long) ").append(readExpr);
            case "long", "java.lang.Long" -> sb.append(readExpr);
            case "double", "java.lang.Double" -> sb.append(readExpr);
            case "float", "java.lang.Float" -> sb.append("(double) ").append(readExpr);
            case "boolean", "java.lang.Boolean" -> sb.append(readExpr);
            case "short", "java.lang.Short" -> sb.append("(long) ").append(readExpr);
            case "byte", "java.lang.Byte" -> sb.append("(long) ").append(readExpr);
            case "java.math.BigDecimal" -> sb.append("JqNumber.of(").append(readExpr).append(")");
            default -> sb.append("io.hyperfoil.tools.jjq.mapper.TypeConverter.toJqValue(")
                         .append(readExpr).append(", mapper)");
        }
    }

    /**
     * Generate the Java source for a {@code JqMappingRegistry} class that
     * registers all generated mappings in a single method call.
     *
     * <p>Usage:</p>
     * <pre>{@code
     * JqMapper.Builder builder = JqMapper.builder();
     * JqMappingRegistry.registerAll(builder);
     * JqMapper mapper = builder.build();
     * }</pre>
     *
     * @param packageName        the package for the registry class
     * @param mappingClassNames  simple class names of generated mappings (e.g., "User_JqMapping")
     * @return the complete Java source for the registry class
     */
    static String generateRegistry(String packageName, List<String> mappingClassNames) {
        var sb = new StringBuilder(512);

        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        sb.append("import io.hyperfoil.tools.jjq.mapper.JqMapper;\n\n");

        sb.append("/**\n");
        sb.append(" * Generated registry for all {@code @JqMapped} records in this package.\n");
        sb.append(" * Do not edit — regenerated by jjq-mapper-processor.\n");
        sb.append(" *\n");
        sb.append(" * <p>Usage:</p>\n");
        sb.append(" * <pre>{@code\n");
        sb.append(" * JqMapper.Builder builder = JqMapper.builder();\n");
        sb.append(" * JqMappingRegistry.registerAll(builder);\n");
        sb.append(" * JqMapper mapper = builder.build();\n");
        sb.append(" * }</pre>\n");
        sb.append(" */\n");
        sb.append("public final class JqMappingRegistry {\n\n");
        sb.append("    private JqMappingRegistry() {}\n\n");
        sb.append("    /**\n");
        sb.append("     * Register all generated mappings from this package with the given builder.\n");
        sb.append("     *\n");
        sb.append("     * @param builder the mapper builder to register mappings with\n");
        sb.append("     */\n");
        sb.append("    public static void registerAll(JqMapper.Builder builder) {\n");

        for (String mappingClassName : mappingClassNames) {
            sb.append("        builder.register(new ").append(mappingClassName).append("());\n");
        }

        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }
}
